### PR TITLE
Animals table

### PR DESCRIPTION
**Pull request by SimbaWANGU**
In this Pull Request, the following changes were introduced:
1. Create a database 'vetclinic'
2. Created table and populated it with the following data:
    - Animal: His name is Agumon. He was born on Feb 3rd, 2020, and currently weighs 10.23kg. He was neutered and he has never tried to escape.
    - Animal: Her name is Gabumon. She was born on Nov 15th, 2018, and currently weighs 8kg. She is neutered and she has tried to escape 2 times.
    - Animal: His name is Pikachu. He was born on Jan 7th, 2021, and currently weighs 15.04kg. He was not neutered and he has tried to escape once.
    - Animal: Her name is Devimon. She was born on May 12th, 2017, and currently weighs 11kg. She is neutered and she has tried to escape 5 times.
3. Run the following queries:
- Find all animals whose name ends in "mon".
contains 'mon'

- List the name of all animals born between 2016 and 2019.
between 2016 amd 2019

- List the name of all animals that are neutered and have less than 3 escape attempts.
neutered and less than 3 escape

- List the date of birth of all animals named either "Agumon" or "Pikachu".
dob of Agumon or Pikachu

- List name and escape attempts of animals that weigh more than 10.5kg
escape attempts more than 5

- Find all animals that are neutered.
neutered animals

- Find all animals not named Gabumon.
not like gabumon

- Find all animals with a weight between 10.4kg and 17.3kg (including the animals with the weights that equals precisely 10.4kg or 17.3kg)
weight greater than or equal to 10 4kg

### CODE REVIEW

**Review by gemmen29 — CHANGES_REQUESTED** [review]
Hi @SimbaWANGU, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯  
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
- [x] Kindly update the README file with your info in the `Project title`, `Project description`, and `Authors` sections.



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SimbaWANGU** [comment]
@gemmen29 thank you for the review, I will work on the requested changes 😄

**Review by ShadyShawkat — APPROVED** [review]
## Hi @SimbaWANGU, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SimbaWANGU** [comment]
Thank you for the approval @ShadyShawkat 👍

**Pull request merged**
